routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('sites', 'SitesController');
Route::get('/vote/{id}', 'SitesController@vote')->name('sites');
Route::post('/vote/add/{id}', 'SitesController@storeVote');
Route::post('/site/store', 'SitesController@store');
Route::post('/visit/add', 'SitesController@storeVisit')->name('visit');
Route::get('/preview_ad/{id}', 'SitesController@previewAd');
/*Route::get('/dashboard', 'SitesController@dashboard')->name('dashboard');*/
Route::get('/dashboard/my_sites', 'SitesController@dashboard')->name('dashboard');
Route::get('/dashboard/my_ads', 'SitesController@myAds')->name('my_ads');
Route::get('/dashboard/my_account', 'SitesController@myAccount')->name('my_account');
Route::post('/dashboard/account/password_update', 'HomeController@postCredentials');
Route::get('/dashboard/ad/create', 'SitesController@adCreate')->name('ad_create');
Route::post('/dashboard/create_ad', 'SitesController@storeAd')->name('store_ad');
Route::post('/ad/{id}/click', 'SitesController@clickAd');
Route::delete('/ad/{id}', 'SitesController@destroyAd');
Route::get('/ad/{id}', 'SitesController@editAd');
Route::get('/buy/{id}', 'PaymentController@buyAd');
Route::patch('/ad/update/{id}', 'SitesController@updateAd');
Route::delete('/category/{id}', 'SitesController@destroyCategory');
Route::post('/category/update/{id}', 'SitesController@updateCategory');
Route::post('/category/check/', 'SitesController@checkCategory');


Route::get('/admin/dashboard', 'AdminController@index')->name('admin');
Route::get('/admin/users', 'AdminController@users')->name('users');
Route::get('/admin/ads', 'AdminController@ads')->name('ads');
Route::post('/ad/{id}/activate', 'AdminController@changeStatusAd')->name('activatead');
Route::patch('/admin/status/{id}', 'AdminController@changeStatus')->name('status');
Route::post('/user/{id}/ban', 'AdminController@banUser');
Route::post('/user/{id}/unban', 'AdminController@unbanUser')->name('unban');
Route::post('/user/info/{id}', 'AdminController@userInfo')->name('userinfo');
Route::delete('/user/{id}', 'AdminController@destroyUser');
Route::post('/user/', 'AdminController@createUser')->name('createuser');
Route::post('/user/emailcheck', 'AdminController@checkEmail');
Route::post('/user/{id}/info', 'AdminController@user');
Route::post('/user/{id}', 'AdminController@userUpdate');
Route::get('/admin/sites/categories', 'SitesController@categories');
Route::post('/admin/category/create', 'SitesController@createCategory')->name('create_category');
Route::get('/admin/premium', 'SitesController@premium');
Route::post('/admin/premium/create', 'SitesController@createPremium')->name('create_premium');


Route::get('/dashboard/premium', 'SitesController@editAd');
// route for view/blade file
Route::get('/dashboard/premium', array('as' => 'paywithpaypal','uses' => 'PaymentController@payWithPaypal',));
// route for post request
Route::post('paypal', array('as' => 'paypal','uses' => 'PaymentController@postPaymentWithpaypal',));
// route for check status responce premium pay
Route::get('paypal', array('as' => 'statusPremium','uses' => 'PaymentController@getPaymentStatusPremium',));
// route for check status responce ad pay
Route::get('paypal/ad/{id}', 'PaymentController@getPaymentStatusAd');
//Route::get('paypal/{id}', 'PaymentController@getPaymentStatusAd');

resources/views/admin/ads.blade.php
@extends('layouts.app')
@section('content')
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.js"></script>
<div class="container-fluid">
    <div class="row">
        @include('layouts.admin_sidebar')
        <div class="col-md-10">
            @if(session()->has('message'))
                <div class="alert alert-success">
                    <center><h3>{{ session()->get('message') }}</h3></center>
                </div>
            @endif
            <div class="card mb-3">
              <div class="card-header">My Ads</div>
                <div class="tab-content" id="v-pills-tabContent">
                  <!-- TAB MY ADS -->
                  <div class="tab-pane active m-3" id="t-my-ads" role="tabpanel" aria-labelledby="my-ads-tab">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <h1 class="float-left">My Ads</h1><a href="{{ url('/dashboard/ad/create') }}" class="btn btn-danger float-right mb-2" title="Create new Site" target="blank"><i class="fas fa-plus"></i> New Ad</a>
                          <thead>
                            <tr>
                              <th scope="col">#</th>
                              <th scope="col">Title</th>
                              <th scope="col">User</th>
                              <th scope="col">Expires</th>
                              <th scope="col">Spot</th>
                              <th scope="col">Status</th>
                              <th scope="col">Views</th>
                              <th scope="col">Clics</th>
                              <th scope="col">Action</th>
                              <th scope="col">Active</th>
                            </tr>
                          </thead>
                          <tbody>
                            @foreach($my_ads as $ad)
                            <tr>
                                <th>#</th>
                                <th>{{ $ad->tittle }}</th>
                                 <th>{{ $ad->user['name'] }}</th>
                                @if($ad->active === 1)
                                <th>{{ $diff = Carbon\Carbon::parse($ad->end_ad)->diffInDays(Carbon\Carbon::now()) }} days</th>
                                @else
                                <th class="text-center">-</th>
                                @endif
                                <th>{{ $ad->spots['name'] }}</th>
                                <th>@if($ad->active == 1) <span class="badge badge-success">ACTIVE</span> @else <span class="badge badge-danger">INACTIVE</span> @endif</th>
                                <th>{{ $ad->views }}</th>
                                <th>{{ $ad->clicks }}</th>
                                <th><div class="btn-group inline pull-left">
                                    <div class="inner"><a href="{{ URL::to('/preview_ad/'.$ad->id)}}" class="btn btn-primary mr-1" title="Preview Ad"><i class="far fa-eye"></i></a></div>
                                    <div class="inner"><a href="{{ URL::to('ad/'.$ad->id)}}" class="btn btn-success mr-1" title="Edit Ad"><i class="fas fa-edit"></i></a></div>
                                    <div class="inner">
                                      <a href="javascript:;" data-toggle="modal" onclick="deleteAd({{$ad->id}})"
                                          data-target="#delete" class="btn btn-xs btn-danger mr-1" title="Delete Ad"><i class="far fa-trash-alt"></i></a>
                                    </div>
                                </div></th>
                                <th>
                                  <div class="btn-group inline pull-left">
                                    <div class="inner">
                                      <form action="{{ route('activatead', $ad->id) }}" method="POST">
                                        {{csrf_field()}} 
                                        <input type="number" name="approve" hidden="hidden" value="1">
                                        <button type="submit" class="btn btn-success mr-1" title="Active ad"><i class="fas fa-check"></i></button>
                                      </form>
                                    </div>
                                    <div class="inner">
                                        <form action="{{ route('activatead', $ad->id) }}" method="POST">
                                        {{csrf_field()}} 
                                        <input type="number" name="approve" hidden="hidden" value="0">
                                        <button type="submit" class="btn btn-danger mr-1" title="Desactive ad"><i class="fas fa-ban"></i></button>
                                      </form>
                                    </div>
                                </div>
                              </th>
                            </tr>
                            @endforeach
                          </tbody>
                        </table>
                    </div>
                  </div>
                  </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-confirm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="icon-box">
          <i class="fas fa-exclamation-circle"></i>
        </div>  
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h3 class="text-center">Are you sure you want to delete this?</h3>
        <form class="delete" method="POST" id="deleteFormAd">
          <input type="hidden" name="_method" value="DELETE">
            {{ csrf_field() }}
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger" onclick="formSubmit()">Delete</button>
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/admin/categories.blade.php
@extends('layouts.app')
@section('content')
<div class="container-fluid">
    <div class="row">
        @include('layouts.admin_sidebar')
        <div class="col-md-10">
            @if(session()->has('message'))
                <div class="alert alert-success">
                    <center><h3>{{ session()->get('message') }}</h3></center>
                </div>
            @endif
            <div class="card mb-3">
              <div class="card-header">Categories</div>
                <div class="tab-content" id="v-pills-tabContent">
                  <!-- TAB MY SITES -->
                  <div class="tab-pane fade show active m-3" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
                    <div class="row">
                      <div class="col-md-8">
                        <div class="table-responsive">
                        <table class="table table-striped">
                            <h1 class="float-left">Categories</h1>
                          <thead>
                            <tr>
                              <th scope="col">#</th>
                              <th scope="col">Name</th>
                              <th scope="col">Image</th>
                              <th scope="col">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            @foreach($categories as $category)
                            <tr>
                                <th>#</th>
                                <th>{{ $category->name }}</th>
                                <th><img src="{{$category->image}}" style="height: 60px; width: 100px"></th>
                                <th><div class="btn-group inline pull-left">
                                    <div class="inner"><a href="#" class="btn btn-primary mr-1 edit-category" data-id="{{$category->id}}" data-toggle="modal" data-target="#category-modal" title="Edit Cateogry" data-name="{{$category->name}}" data-image="{{$category->image}}"><i class="far fa-eye"></i></a></div>
                                    <div class="inner"><a href="#" class="btn btn-success mr-1 edit-category" data-id="{{$category->id}}" data-toggle="modal" data-target="#category-modal" title="Edit Cateogry" data-name="{{$category->name}}" data-image="{{$category->image}}"><i class="fas fa-edit"></i></a></div>
                                    <div class="inner">
                                      <a href="javascript:;" data-toggle="modal" onclick="deleteCategory({{$category->id}})" 
                                          data-target="#delete" class="btn btn-xs btn-danger" title="Delete Site"><i class="far fa-trash-alt"></i></a>
                                    </div>
                                </div></th>
                            </tr>
                            @endforeach
                          </tbody>
                        </table>
                    </div>
                      </div>
                      <div class="col-md-4">
                        <div><h1>Create Category</h1></div>
                          <form action="{{ url('/admin/category/create') }}" method="POST" enctype="multipart/form-data" id="add-category">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}"> 
                            <div class="form-group">
                              <label>Banner</label>
                            <input type="file" class="form-control-file{{ $errors->has('banner') ? ' border-fail' : '' }}" id="banner" name="banner">
                              <small id="fileHelp" class="form-text text-muted" style="font-size: 0.7vw">The file must be, JPG,JPEG,PNG or GIF. Maximun size: 5MB</small>
                              </div>
                              <div class="form-group">
                                <label>URL</label>
                                <input type="text" class="form-control{{ $errors->has('banner_link') ? ' is-invalid' : '' }}" id="banner_link" name="banner_link" placeholder="https://yourdomain.com/image.jpg">
                              </div>
                            <label>Category</label>
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" placeholder="Category" name="category" id="category-name" required="required">
                              <div class="input-group-append">
                                <button class="btn btn-success add-category" type="button">Add</button>
                              </div>
                            </div>
                        </form>
                      </div>
                    </div>
                  </div>
                  </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-confirm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="icon-box">
          <i class="fas fa-exclamation-circle"></i>
        </div>  
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h3 class="text-center">Are you sure you want to delete this?</h3>
        <form class="delete" method="POST" id="deleteFormCategory">
          <input type="hidden" name="_method" value="DELETE">
            {{ csrf_field() }}
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger" onclick="formSubmitCategory()">Delete</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="category-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-confirm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="icon-box">
        </div>  
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h3 class="text-center">Update Category</h3>
        <div id="loading-update" class="text-center" style="display: none">
          <img src="http://top.test/images/loading.gif">
        </div>
        <form method="POST" id="category-form" enctype="multipart/form-data">
          {{ csrf_field() }}
          <div class="form-group row">
            <label for="name">Name</label>
            <input type="text" class="form-control" name="name" id="name-category" aria-describedby="emailHelp" placeholder="Name">
          </div>
          <div class="form-group row">
            <label for="name">Image</label>
            <img id="banner-image" class="img-fluid">
          </div>
          <div class="form-group row">
            <label>Banner</label>
            <input type="file" class="form-control-file{{ $errors->has('banner') ? ' border-fail' : '' }}" id="banner" name="banner">
            <small id="fileHelp" class="form-text text-muted" style="font-size: 0.7vw">The file must be, JPG,JPEG,PNG or GIF. Maximun size: 5MB</small>
          </div>
          <div class="form-group row">
            <label for="image">Image</label>
            <input type="text" class="form-control" name="banner_link" id="image-category" aria-describedby="emailHelp" placeholder="Url">
          </div>
          <button type="submit" class="btn btn-primary">Update</button>
        </form>
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/admin/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container-fluid">
    <div class="row">
        @include('layouts.admin_sidebar')
        <div class="col-md-10">
            @if(session()->has('message'))
                <div class="alert alert-success">
                    <center><h3>{{ session()->get('message') }}</h3></center>
                </div>
            @endif
            <div class="card mb-3">
              <div class="card-header">Sites</div>
                <div class="tab-content" id="v-pills-tabContent">
                  <!-- TAB MY SITES -->
                  <div class="tab-pane fade show active m-3" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <h1 class="float-left">Sites</h1><a href="{{ route('sites.create') }}" class="btn btn-danger float-right mb-2" title="Create new Site" target="blank"><i class="fas fa-plus"></i> New Site</a>
                          <thead>
                            <tr>
                              <th scope="col">#</th>
                              <th scope="col">Title</th>
                              <th scope="col">Owner</th>
                              <th scope="col"><center>Premium</center></th>
                              <th scope="col"><center>Status</center></th>
                              <th scope="col">Category</th>
                              <th scope="col">Action</th>
                              <th scope="col">Status</th>
                            </tr>
                          </thead>
                          <tbody>
                            @foreach($sites as $site)
                            <tr>
                                <th>#</th>
                                <th>{{ $site->title }}</th>
                                <th>{{ $site->user['name'] }}</th>
                                <th><center>@if($site->user['premium'] == 1) <span class="badge badge-success">Yes</span>@else <span class="badge badge-danger">No</span></center> @endif</th>
                                <th><center>@if($site->status['name'] == "Active") <span class="badge badge-success">{{$site->status['name']}}</span>@elseif($site->status['name'] == "Pending") <span class="badge badge-warning">{{$site->status['name']}}</span> @else <span class="badge badge-danger">{{$site->status['name']}}</span></center> @endif</th>
                                <th>{{ $site->category['name'] }}</th>
                                <th><div class="btn-group inline pull-left">
                                    <div class="inner"><a href="{{ route('sites.show', $site->id) }}" class="btn btn-primary mr-1" title="View Site"><i class="far fa-eye"></i></a></div>
                                    <div class="inner"><a href="{{ route('sites.edit', $site->id) }}" class="btn btn-success mr-1" title="Edit Site"><i class="fas fa-edit"></i></a></div>
                                    <div class="inner">
                                      <a href="javascript:;" data-toggle="modal" onclick="deleteData({{$site->id}})" 
                                          data-target="#delete" class="btn btn-xs btn-danger" title="Delete Site"><i class="far fa-trash-alt"></i></a>
                                    </div>
                                </div></th>
                                <!--<th>
                                  <div class="btn-group inline pull-left">
                                    <div class="inner">
                                      <form action="{{ route('status', $site->id) }}" method="POST">
                                        {{csrf_field()}} 
                                        {{ method_field('PATCH') }}
                                        <input type="number" name="approve" hidden="hidden" value="1">
                                        <button type="submit" class="btn btn-success mr-1" title="Approve Site"><i class="fas fa-check"></i></button>
                                      </form>
                                    </div>
                                    <div class="inner">
                                      <form action="{{ route('status', $site->id) }}" method="POST">
                                        {{csrf_field()}} 
                                        {{ method_field('PATCH') }}
                                        <button type="submit" class="btn btn-danger mr-1" title="Ban Site"><i class="fas fa-ban"></i></button>
                                      </form>
                                    </div>
                                </div>
                              </th>-->
                              <th>
                                  <div class="btn-group inline pull-left">
                                    <div class="inner">
                                      <form action="{{ route('status', $site->id) }}" method="POST" class="form-inline">
                                        {{csrf_field()}} 
                                        {{ method_field('PATCH') }}
                                        <div>
                                          <select id="status" class="js-example-basic-single js-states form-control col-md-12" name="status" required="required" style="width: 100%">
                                            @foreach($status as $statu)
                                            <option value={{$statu->id}}>{{ $statu->name }}</option>
                                            @endforeach
                                          </select> 
                                        </div>
                                        <div class="ml-2">
                                          <button type="submit" class="btn btn-success mr-1" title="Approve Site"><i class="fas fa-check"></i></button>
                                        </div>
                                      </form>
                                    </div>
                                </div>
                              </th>
                            </tr>
                            @endforeach
                          </tbody>
                        </table>
                    </div>
                  </div>
                  </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-confirm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="icon-box">
          <i class="fas fa-exclamation-circle"></i>
        </div>  
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h3 class="text-center">Are you sure you want to delete this?</h3>
        <form class="delete" method="POST" id="deleteForm">
          <input type="hidden" name="_method" value="DELETE">
            {{ csrf_field() }}
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger" onclick="formSubmitSite()">Delete</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="edit-site" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-confirm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="icon-box">
          <i class="fas fa-exclamation-circle"></i>
        </div>  
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h3 class="text-center">Are you sure you want to delete this?</h3>
        <form class="delete" method="POST" id="deleteForm">
          <input type="hidden" name="_method" value="DELETE">
            {{ csrf_field() }}
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger" onclick="formSubmitSite()">Delete</button>
      </div>
    </div>
  </div>
</div>

@endsection