routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('sites', 'SitesController');
Route::get('/vote/{id}', 'SitesController@vote')->name('sites');
Route::post('/vote/add/{id}', 'SitesController@storeVote');
Route::post('/site/store', 'SitesController@store');
Route::post('/visit/add', 'SitesController@storeVisit')->name('visit');
Route::get('/preview_ad/{id}', 'SitesController@previewAd');
/*Route::get('/dashboard', 'SitesController@dashboard')->name('dashboard');*/
Route::get('/dashboard/my_sites', 'SitesController@dashboard')->name('dashboard');
Route::get('/dashboard/my_ads', 'SitesController@myAds')->name('my_ads');
Route::get('/dashboard/my_account', 'SitesController@myAccount')->name('my_account');
Route::post('/dashboard/account/password_update', 'HomeController@postCredentials');
Route::get('/dashboard/ad/create', 'SitesController@adCreate')->name('ad_create');
Route::post('/dashboard/create_ad', 'SitesController@storeAd')->name('store_ad');
Route::post('/ad/{id}/click', 'SitesController@clickAd');
Route::delete('/ad/{id}', 'SitesController@destroyAd');
Route::get('/ad/{id}', 'SitesController@editAd');
Route::get('/buy/{id}', 'PaymentController@buyAd');
Route::patch('/ad/update/{id}', 'SitesController@updateAd');
Route::delete('/category/{id}', 'SitesController@destroyCategory');
Route::post('/category/update/{id}', 'SitesController@updateCategory');
Route::post('/category/check/', 'SitesController@checkCategory');


Route::get('/admin/dashboard', 'AdminController@index')->name('admin');
Route::get('/admin/users', 'AdminController@users')->name('users');
Route::get('/admin/ads', 'AdminController@ads')->name('ads');
Route::post('/ad/{id}/activate', 'AdminController@changeStatusAd')->name('activatead');
Route::patch('/admin/status/{id}', 'AdminController@changeStatus')->name('status');
Route::post('/user/{id}/ban', 'AdminController@banUser');
Route::post('/user/{id}/unban', 'AdminController@unbanUser')->name('unban');
Route::post('/user/info/{id}', 'AdminController@userInfo')->name('userinfo');
Route::delete('/user/{id}', 'AdminController@destroyUser');
Route::post('/user/', 'AdminController@createUser')->name('createuser');
Route::post('/user/emailcheck', 'AdminController@checkEmail');
Route::post('/user/{id}/info', 'AdminController@user');
Route::post('/user/{id}', 'AdminController@userUpdate');
Route::get('/admin/sites/categories', 'SitesController@categories');
Route::post('/admin/category/create', 'SitesController@createCategory')->name('create_category');
Route::get('/admin/premium', 'SitesController@premium');
Route::post('/admin/premium/create', 'SitesController@createPremium')->name('create_premium');


Route::get('/dashboard/premium', 'SitesController@editAd');
// route for view/blade file
Route::get('/dashboard/premium', array('as' => 'paywithpaypal','uses' => 'PaymentController@payWithPaypal',));
// route for post request
Route::post('paypal', array('as' => 'paypal','uses' => 'PaymentController@postPaymentWithpaypal',));
// route for check status responce premium pay
Route::get('paypal', array('as' => 'statusPremium','uses' => 'PaymentController@getPaymentStatusPremium',));
// route for check status responce ad pay
Route::get('paypal/ad/{id}', 'PaymentController@getPaymentStatusAd');
//Route::get('paypal/{id}', 'PaymentController@getPaymentStatusAd');

app/Sites.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Sites;
use App\Category;
use App\Status;


class Sites extends Model
{
    //

    protected $table = "sites";

    protected $fillable = [
        'title', 'description', 'category_id', 'url', 'url_file', 'p_description', 'status_id', 'tags'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function status(){
        return $this->belongsTo(Status::class);
    }

}

app/Http/Controllers/SitesController.php
<?php

namespace App\Http\Controllers;

use App\Sites;
use App\Category;
use App\Ad;
use App\User;
use Illuminate\Http\Request;
use DB;
use Carbon;
use Auth;
use Redirect;
use Session;
use Validator;
use URL;
use App\Http\Requests\SiteStoreRequest;
use App\Http\Requests\AdStoreRequest;
use App\Http\Requests\VoteStoreRequest;

class SitesController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index','show', 'vote', 'storeVote']]);
        $this->middleware('banned');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sites = DB::table('sites')->where('status_id', 1)->orderBy('votes','desc')->simplePaginate(15)->status;
        $ads = Ad::inRandomOrder()->limit(6)->where('active', 1)->get();
        

        return view('sites.index', compact('sites', 'ads'));  
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = DB::table('categories')->get();
        return view('sites.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SiteStoreRequest $request)
    {
        $url = request('website');
        $parse = parse_url($url);
        if(request('tags')){
            $tags = request('tags');
            $tags = (implode($tags,','));
        }else{
            $tags = "";
        }
        
        $check_site = DB::table('sites')->where('url', 'like', '%'. $parse['host'] . '%')->get();

        if(count($check_site)){
             return Redirect::back()->with('message', 'This Server alredy exists.');
        }else{
            $user = Auth::user();
            if($request->file('banner')){
                $file = $request->file('banner');
                $destinationPath = 'images/'.$user->name;
                $file->move($destinationPath,$file->getClientOriginalName());
                $url_file = $destinationPath.'/'.$file->getClientOriginalName();
            }else{
                $url_file = "";   
            }

            /*------ THIS I WILL USE IT WHEN THE SITE IS ACTIVATED. IT WILL AUTOMATICALLY GET A RANK --------*/
            //$rank = DB::table('sites')->select('rank')->orderBy('votes', 'asc')->orderBy('created_at', 'asc')->where('status_id', 1)->first();
            /*if(!$rank['rank']){
                $rank = 1;
            }*/

            if(Auth::user()->end_premium < Carbon\Carbon::now()){
                $premium = 0;
            }else{
                $premium = 1;
            }
             $data = DB::table('sites')
                    ->insert([
                        'title' => request('title'),
                        'description' => request('description'),
                        'p_description' => request('p_description'),
                        'url' => request('website'),
                        'category_id' => request('category'),
                        'tags' => $tags,
                        'status_id' => 3,
                        'votes' => 0,
                        //'rank' => $rank[rank]+1,
                        'premium' => $premium,
                        'user_id' => $user->id,
                        'url_file' => $url_file,
                        'created_at' => Carbon\Carbon::now(),
                        'updated_at' => Carbon\Carbon::now(),
                    ]); 

            return redirect()->back()->with('message', 'Site created.');      
            
        }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Sites  $sites
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $site = Sites::findOrFail($id);
        if($site->status_id == 1 || $site->user_id == Auth::id()){
        $user = $site->user;

        $chartjs = app()->chartjs
        ->name('lineChartTest')
        ->type('bar')
        ->size(['width' => 400, 'height' => 350])
        ->labels(['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October' , 'November' ,'December'])
        ->datasets([
            [
                "label" => "Votes",
                'backgroundColor' => "rgba(38, 185, 154, 0.31)",
                'borderColor' => "rgba(38, 185, 154, 0.7)",
                "pointBorderColor" => "rgba(38, 185, 154, 0.7)",
                "pointBackgroundColor" => "rgba(38, 185, 154, 0.7)",
                "pointHoverBackgroundColor" => "#fff",
                "pointHoverBorderColor" => "rgba(220,220,220,1)",
                'data' => [65, 59, 80, 81, 56, 55, 40],
            ],
            [
                "label" => "Visits",
                'backgroundColor' => "rgba(233, 67, 67, 0.8)",
                'borderColor' => "rgba(38, 185, 154, 0.7)",
                "pointBorderColor" => "rgba(38, 185, 154, 0.7)",
                "pointBackgroundColor" => "rgba(38, 185, 154, 0.7)",
                "pointHoverBackgroundColor" => "#fff",
                "pointHoverBorderColor" => "rgba(220,220,220,1)",
                'data' => [12, 33, 44, 44, 55, 23, 40],
            ]
        ])
        ->options([]);

        return view('sites.view', compact('site','user','chartjs'));  
        }
        else{
            return redirect()->back();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Sites  $sites
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Auth::user()->admin()){
            $site = Sites::findOrFail($id);
            $user = $site->user;
            $categories = Category::all();
        }else{
            $site = Sites::where('user_id', Auth::user()->id)->findOrFail($id);
            $user = $site->user;
            $categories = Category::all();
        } 

        $users = User::all();

        return view('sites.edit', compact('site','user','categories', 'users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Sites  $sites
     * @return \Illuminate\Http\Response
     */
    public function update(SiteStoreRequest $request, $id)
    {

        if(Auth::user()->admin()){
            $site = Sites::findOrFail($id);

            $user = Auth::user();

            $owner = $user->id;

            if(request('owner') != null){
                $owner = request('owner');
            }

            if(request('tags')){
                $tags = request('tags');
                $tags = (implode($tags,','));
            }else{
                $tags = "";
            }
            if($request->file('banner')){
                $file = $request->file('banner');
                $destinationPath = 'images/'.$user->name;
                $file->move($destinationPath,$file->getClientOriginalName());
                $url_file = $destinationPath.'/'.$file->getClientOriginalName();
            }else{
                $url_file = $site->url_file;   
            }  

            DB::table('sites')
                ->where('id', $id)
                ->update([
                    'title' => request('title'),
                    'description' => request('description'),
                    'p_description' => request('p_description'),
                    'category_id' => request('category'),
                    'url' => request('website'),
                    'url_file' => $url_file,
                    'tags' => $tags,
                    'user_id' => $owner,
            ]);

        }else{
            $site = Sites::where('user_id', Auth::user()->id)->findOrFail($id);

            $user = Auth::user();

            if(request('tags')){
                $tags = request('tags');
                $tags = (implode($tags,','));
            }else{
                $tags = "";
            }
            if($request->file('banner')){
                $file = $request->file('banner');
                $destinationPath = 'images/'.$user->name;
                $file->move($destinationPath,$file->getClientOriginalName());
                $url_file = $destinationPath.'/'.$file->getClientOriginalName();
            }else{
                $url_file = $site->url_file;   
            }        

            DB::table('sites')
                ->where('id', $id)
                ->update([
                    'title' => request('title'),
                    'description' => request('description'),
                    'p_description' => request('p_description'),
                    'category_id' => request('category'),
                    'url' => request('website'),
                    'url_file' => $url_file,
                    'tags' => $tags,
            ]);
        }
        

        return redirect()->back()->with('message', 'Site updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Sites  $sites
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Auth::user()->admin()){
            $site = Sites::findOrFail($id);

            $site->delete();

        }else{
            $site = Sites::where('user_id', Auth::user()->id)->findOrFail($id);

            $site->delete();
        }
        

        return redirect()->back()->with('message', 'Site deleted.');
    }

    public function vote($id)
    {
        $site = Sites::findOrFail($id);
        if($site->status_id != 1){
            return redirect()->back();
        }
        else{
            return view('sites.vote', compact('site'));
        }
        
    }

    public function storeVote(VoteStoreRequest $request, $id)
    {   

        if (Sites::find($id)) {

resources/views/sites/dashboard.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="card mb-3">
              <div class="card-header">Dashboard</div>
                <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                  <a class="nav-link active" href="{{  url('/dashboard/my_sites') }}" >My Sites</a>
                  <a class="nav-link" href="{{ route('sites.create') }}" aria-selected="true">New Site</a>
                  <div class="card-header">Premium</div>
                  <a class="nav-link" href="{{  url('/dashboard/premium') }}" aria-selected="false">Buy Premium</a>
                  <div class="card-header">Ads</div>
                  <a class="nav-link" href="{{  url('/dashboard/my_ads') }}" >My Ads</a>
                  <a class="nav-link" href="{{ url('/dashboard/ad/create') }}" aria-selected="true">New Ad</a>
                  <div class="card-header">My Account</div>
                  <a class="nav-link" href="{{  url('/dashboard/my_account') }}" aria-selected="false">Account</a>
                  <a class="nav-link" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>
                  <form id="logout-form-dashboard" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            @if(session()->has('message'))
                <div class="alert alert-success">
                    <center><h3>{{ session()->get('message') }}</h3></center>
                </div>
            @endif
            <div class="card mb-3">
              <div class="card-header">My Sites</div>
                <div class="tab-content" id="v-pills-tabContent">
                  <!-- TAB MY SITES -->
                  <div class="tab-pane fade show active m-3" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <h1 class="float-left">My Sites</h1><a href="{{ route('sites.create') }}" class="btn btn-danger float-right mb-2" title="Create new Site"><i class="fas fa-plus"></i> New Site</a>
                          <thead>
                            <tr>
                              <th scope="col">#</th>
                              <th scope="col">Title</th>
                              <th scope="col"><center>Premium</center></th>
                              <th scope="col"><center>Status</center></th>
                              <th scope="col">Category</th>
                              <th scope="col">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            @foreach($sites as $site)
                            <tr>
                                <th>#</th>
                                <th>{{ $site->title }}</th>
                                <th><center>@if($site->user['premium'] == 1) <span class="badge badge-success">Yes</span>@else <span class="badge badge-danger">No</span></center> @endif</th>
                                <th><center>@if($site->status['name'] == "Active") <span class="badge badge-success">{{$site->status['name']}}</span>@elseif($site->status['name'] == "Pending") <span class="badge badge-warning">{{$site->status['name']}}</span> @else <span class="badge badge-danger">{{$site->status['name']}}</span></center> @endif</th>
                                <th>{{ $site->category['name'] }}</th>
                                <th><div class="btn-group inline pull-left">
                                    <div class="inner"><a href="{{ route('sites.show', $site->id) }}" class="btn btn-primary mr-1" title="View Site"><i class="far fa-eye"></i></a></div>
                                    <div class="inner"><a href="{{ route('sites.edit', $site->id) }}" class="btn btn-success mr-1" title="Edit Site"><i class="fas fa-edit"></i></a></div>
                                    <div class="inner">
                                      <a href="javascript:;" data-toggle="modal" onclick="deleteData({{$site->id}})" 
                                          data-target="#delete" class="btn btn-xs btn-danger" title="Delete Site"><i class="far fa-trash-alt"></i></a>
                                    </div>
                                </div></th>
                            </tr>
                            @endforeach
                          </tbody>
                        </table>
                    </div>
                  </div>
                  </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-confirm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="icon-box">
          <i class="fas fa-exclamation-circle"></i>
        </div>  
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h3 class="text-center">Are you sure you want to delete this?</h3>
        <form class="delete" method="POST" id="deleteForm">
          <input type="hidden" name="_method" value="DELETE">
            {{ csrf_field() }}
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger" onclick="formSubmitSite()">Delete</button>
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/sites/edit.blade.php
@extends('layouts.app')
@section('content')
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.js"></script>
<div class="container">
    <div class="row">
        <div class="col-md-8">
          <div>
              {{ Breadcrumbs::render('edit_site', $site) }}
            </div>
            @if(session()->has('message'))
                <div class="alert alert-success">
                    <center><h3>{{ session()->get('message') }}</h3></center>
                </div>
            @endif
            <form action="{{URL::route('sites.update', $site->id)}}" method="POST" enctype="multipart/form-data">
                {{ method_field('PATCH') }}
              <input type="hidden" name="_token" value="{{ csrf_token() }}">
              <div class="form-row">
                 @if(Auth::user()->admin())
                <div class="form-group col-md-12">
                  <label for="website" style="font-size: 1vw">Owner</label>
                  <select class="form-control" name="owner">
                    @foreach($users as $user)
                    @if($site->user_id == $user->id)
                    <option value="{{$user->id}}" selected="selected">{{$user->name}}</option>
                    @endif
                    <option value="{{$user->id}}">{{$user->name}}</option>
                    @endforeach
                  </select>
                </div>
                @endif
                <div class="form-group col-md-12">
                  <label for="category" style="font-size: 1vw">Category</label>
                  <select id="category" class="js-example-basic-single js-states form-control" name="category" required="required" style="width: 100%">
                    <option selected="selected" value="">Choose...</option>
                    @foreach($categories as $category)
                    @if($site->category['name'] == $category->name)
                    <option value="{{$category->id}}" selected="selected">{{$category->name}}</option>
                    @else
                    <option value="{{$category->id}}">{{$category->name}}</option>
                    @endif
                    @endforeach
                  </select>
                    @if ($errors->has('category'))
                        <div class="error">{{ $errors->first('category') }}</div>
                    @endif
                </div>
                <div class="form-group col-md-12">
                  <label for="title" style="font-size: 1vw">Title</label>
                  <input type="text" class="form-control" id="title" name="title" placeholder="Title" required="required"  minlength="5" maxlength="100" value="{{ $site->title }}">
                  @if ($errors->has('title'))
                    <div class="error">{{ $errors->first('title') }}</div>
                  @endif
                </div>
              </div>
              <div class="form-group">
                <label for="description" style="font-size: 1vw">Description</label>
                <textarea class="form-control" rows="3" id="description" name="description" placeholder="Description" required="required" minlength="15" maxlength="255">{{ $site->description }}</textarea>
                @if ($errors->has('description'))
                    <div class="error">{{ $errors->first('description') }}</div>
                @endif
              </div>
              <div class="form-group">
                <label for="website" style="font-size: 1vw">Website</label>
                <input type="text" class="form-control{{($errors->first('website') ? " form-error" : "")}}" id="website" name="website" placeholder="https://top.test/" required="required" minlength="8" maxlength="100" value="{{ $site->url }}">
                @if ($errors->has('website'))
                    <div class="error">{{ $errors->first('website') }}</div>
                @endif
              </div>
              <div class="form-row">
                <div class="form-group col-md-12">
                  <label for="category" style="font-size: 1vw">Tags</label>
                  <select id="tags" class="form-control" name="tags[]" multiple="multiple" style="width: 100%">
                  @if($site->tags)
                  @foreach(explode(',', $site->tags) as $tag) 
                        <option value="{{ $tag }}" selected="selected">{{ $tag }}</option>    
                  @endforeach
                  @endif              
                  </select>
                    @if ($errors->has('tags'))
                        <div class="error">{{ $errors->first('tags') }}</div>
                    @endif
                  <small id="tagsHelp" class="form-text text-muted" style="font-size: 0.7vw">Example: 3.3.5, Custom, Fun, Blizzlike...</small>
                </div>
              </div>
              <div class="form-row">
                <div class="form-group col-md-12">
                  <label for="category" style="font-size: 1vw">Premium description</label>
                    <textarea id="summernote" name="p_description">{!! $site->p_description !!}</textarea>
                    <small id="tagsHelp" class="form-text text-muted" style="font-size: 0.7vw">This will be seen in server page. Only availabe for premium users.</small>
                </div>
              </div>
              <div class="form-row">
                <div class="form-group col-md-12">
                  <label for="banner" style="font-size: 1vw">Premium Banner</label>
                  <div>
                    @if($site->url_file)
                    <img class="img-fluid mb-1" style="width: 468px; height: 60px;" src="{{ URL::to('/')."/".$site->url_file }}">
                    @endif
                </div>
                    <input type="file" class="form-control-file" id="banner" name="banner">
                    <small id="fileHelp" class="form-text text-muted" style="font-size: 0.7vw">The file must be, JPG,JPEG,PNG or GIF. Maximun size: 5MB</small>
                    @if ($errors->has('banner'))
                        <div class="error">{{ $errors->first('banner') }}</div>
                    @endif
                </div>
              </div>
              <div class="form-row">
                <div class="col-md-6 col-md-6 mb-2">
                    {!! NoCaptcha::display() !!}
                </div>
                </div>
                @if ($errors->has('g-recaptcha-response'))
                    <div class="error mb-2"><strong style="color: red">{{ $errors->first('g-recaptcha-response') }}</strong></div>
                @endif
              <button type="submit" class="btn btn-primary mb-2">Submit</button>
            </form>
        </div>
        <div class="col-md-4">
            <div class="card mt-3">
              <div class="card-header">Rules</div>
              <div class="card-body">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item">Not adult or ilegal content.</li>
                  <li class="list-group-item">Do not duplicate same server.</li>
                  <li class="list-group-item">No cheatin, vpn, proxy or bots.</li>
                  <li class="list-group-item">Site must be complete.</li>
                </ul>
              </div>
            </div>
            <div class="card mt-3">
              <div class="card-header">Approval</div>
              <div class="card-body">
                <p class="card-text">You can add all the sites you want but all must be approved manually. We have to verify that each site does not break any rule.</p>
              </div>
            </div>
            <div class="card mb-3 mt-3">
              <div class="card-header">Premium</div>
              <div class="card-body">
                <p class="card-text">You can purchase premium status for your site after you add it. This will give you some features.</p>
              </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/sites/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        
  
            @foreach($ads as $ad)
            <div class="col-md-6">
            <div class="col-md-12">
            <div class="row test">
                <div class="col-md-8 text-center mt-3">
                    <center><a href="{{$ad->website}}" target="_blank" ><img style="width: 468px; height: 60px;" class="img-fluid mb-3 ad-site"   src="{{$ad->banner}}" data-id="{{$ad->id}}">
                    </a></center>
                </div>
                <div class="col-md-4 text-center"style="margin-top: auto; margin-bottom: auto;">
                    <h4>{{$ad->tittle}}</h4>
                </div>
            </div>
            </div>
            </div>
            @endforeach
           
        
    </div>
    <div class="row">
        <div class="col-md-12">
            <hr>
            
            @foreach($sites as $site)
            @if($site->user['premium'] == 1)
                <div class="row test" style="background-color: #f3eed8">
            @else
                <div class="row test">
            @endif
                <div class="col-md-2 text-center">
                    <h1>Rank</h1>
                    <h1 class="center">{{ $site->rank }}</h1>
                </div>
                <div class="col-md-8 text-center">
                    <h4><a href="{{ route('sites.show', $site->id) }}" class="server-title">{{ $site->title }}</a></h4>
                    @if($site->user['premium'] == 1)
                    <center><a href="{{ route('sites.show', $site->id) }}"><img style="width: 468px; height: 60px;" class="img-fluid" src="{{ URL::to('/')."/".$site->url_file }}">
                    </a></center>
                    @else
                    @endif
                    <h7>{{ $site->description }}</h7>
                    <br>
                    @if($site->tags != "")
                    @foreach(explode(',', $site->tags) as $tag) 
                        <span class="badge badge-pill badge-danger mb-1" style="font-size: 0.8vw;">{{ $tag }}</span>
                    @endforeach
                    @endif
                    
                </div>
                <div class="col-md-2 text-center">
                    <h1>Votes</h1>
                    <h1 class="center">{{ $site->votes }}<i class="far fa-thumbs-up"></i></h1>
                </div>
            </div>
            @endforeach
            {{ $sites->links() }}
        </div>
    </div>
</div>
@endsection